version: '2'
services:
  sample:
    build: ./application/
    ports:
     - "80:80"
    volumes:
     - ./app/:/var/www/html
    links:
     - mysql-server
  mysql-server:
    image: mysql:5.7
    volumes:
     - ./db/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Ev0den!!
        MYSQL_USER: root
        MYSQL_PASSWORD: admin123
        MYSQL_DATABASE: idemand4u_ams
